protocol: novel-tls-v1
version: 1
transport:
  type: tls
  host: 127.0.0.1
  port: 19443
  tls:
    version: '1.3'
    fingerprint: chrome-120
    alpn:
    - h2
    - http/1.1
    sni: www.google.com
    cert_file: D:\programs\диплом\llm-eval\results\gpt-4o-mini\f47493d7-c93c-4a1d-8715-7e7bcaa6ad53\server.crt
    key_file: D:\programs\диплом\llm-eval\results\gpt-4o-mini\f47493d7-c93c-4a1d-8715-7e7bcaa6ad53\server.key
    insecure: true
handshake:
  type: tls-token
  tls_token:
    field: session_ticket
    kdf: hkdf-sha256
    psk: b6d0bef42b15f7210b4803cbc28e1a1d472fad5bdee08bc94c9bf78b410fe96d
    length: 48
crypto:
  aead: chacha20-poly1305
  kdf: hkdf-sha256
padding:
  mode: mimicry
  profile: chrome-browsing
timing:
  mode: none
fallback:
  enabled: true
  mode: reverse-proxy
  target: https://www.google.com
