protocol: noise-nnpsk2-v1
version: 1
transport:
  type: tls
  host: 127.0.0.1
  port: 19444
  tls:
    version: '1.3'
    fingerprint: chrome-120
    alpn:
    - h2
    - http/1.1
    sni: www.cloudflare.com
    cert_file: D:\programs\диплом\llm-eval\results\deepseek-chat\7731d652-6e29-43d4-adb9-7e89e183a313\server.crt
    key_file: D:\programs\диплом\llm-eval\results\deepseek-chat\7731d652-6e29-43d4-adb9-7e89e183a313\server.key
    insecure: true
handshake:
  type: noise
  noise:
    pattern: NNpsk2
    cipher_suite: 25519:ChaChaPoly:BLAKE2s
    local_key: generate
    psk: ba5626a422cb523c2f9beca6b91864e9911d2bfd545b0e2a11549025078582f4
crypto:
  aead: chacha20-poly1305
  kdf: hkdf-sha256
padding:
  mode: random
  random_min: 40
  random_max: 1400
timing:
  mode: none
fallback:
  enabled: true
  mode: reverse-proxy
  target: https://www.cloudflare.com
